config/routes.rb
Rails.application.routes.draw do
  get '/project/sections', to: 'homes#index', as: 'get_sections'
  get 'edit/section/:id', to: 'homes#edit', as: 'edit_section'
  post 'update/section/:id', to: 'homes#update', as: 'update_section'
  get '/project/section/new', to: "homes#new", as: 'new_section'
  post '/project/sections', to: 'homes#create', as: 'create_section'
  get '/project/delete/section/:id', to: 'homes#destroy', as: 'destroy_section'
  get '/project/section/task/edit/:id', to: 'homes#edit_task', as: 'edit_task'
  post '/project/section/task/update/:id', to: 'homes#update_section_task', as: 'update_task'
  
  root to: 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
require 'json'
class HomesController < ApplicationController
  include ApiForAsana
  def index
    @code = get_sections.code
    @body = JSON.parse(get_sections.body)
  end
  
  def edit
    @id = params[:id]
  end

  def new
  end

  def edit_task
      @id = params[:id]
  end

    def create
        name = params[:name]
        res = create_section(name)
        if res.code == '201'
          redirect_to get_sections_path, notice: 'Successfuly create section!'
        else
          data = JSON.parse(res.body)
          redirect_to get_sections_path, alert: "#{data["errors"][0]["message"]}"
        end
    end

    def destroy
      id = params[:id]
      res = delete_section(id)
      if res.code == '200'
        redirect_to get_sections_path, notice: 'Successfuly delete section!'
      else
        data = JSON.parse(res.body)
        redirect_to get_sections_path, alert: "Error happened #{data["errors"][0]["message"]}"
      end
    end


    def update
      id = params[:id]
      name = params[:name]
      res = update_section(id, name)
      if res.code == '200'
        redirect_to get_sections_path, notice: "Successfuly update your section to #{name}"
      else
        data = JSON.parse(res.body)
        redirect_to get_sections_path, alert: "#{data["errors"][0]["message"]}"
      end
    end 

    def update_section_task
      id = params[:id]
      name = params[:name]
      res = update_task(id, name)
      if res.code == '200'
        redirect_to get_sections_path, notice: "Successfuly update your task to #{name}"
      else
        data = JSON.parse(res.body)
        redirect_to get_sections_path, alert: "#{data["errors"][0]["message"]}"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
require 'json'
require 'api_for_asana'
module HomesHelper
  include ApiForAsana

  def task_list(id)
    tasks = get_tasks(id)
    JSON.parse(tasks.body)
  end
end

app/views/homes/_header.html.erb
<header>
    <ul>
      <li><%=link_to "Asana Board", get_sections_path %></li>
      <li><%=link_to "Create Section", new_section_path, class:'create' %></li>
    </ul>
</header>

app/views/homes/edit.html.erb
    <%= render "header"%>


    <%= form_with url: "/update/section/#{@id}", method: :post do |form| %>
    <div class='filed'>
    <%= form.label :name, "Section Name" %> <br/><br/>
    <%= form.text_field :name, required: true, placeholder: 'section name' %>
  </div>
    <%= form.submit "Update Section", class: 'btn-link' %>
 <% end %>

app/views/homes/edit_task.html.erb
    <%= render "header"%>


    <%= form_with url: "/project/section/task/update/#{@id}", method: :post do |form| %>
    <div class='filed'>
    <%= form.label :name, "Task Name" %> <br/><br/>
    <%= form.text_field :name, required: true, placeholder: 'section name' %>
  </div>
    <%= form.submit "Update Section", class: 'btn-link' %>
 <% end %>

app/views/homes/index.html.erb
<%= render "header"%>

<div class="title-container">
  <h3>Welcome to your Asana board </h3>
</div>
<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>
<%if @code == '200'%>
<div class="container">
<%@body["data"].each do |section|%>
   <ul class="each-section">
     <div class="top-section">
      <h3><%=section["name"]%></h3>
       <a href="#" class="create-task">+
        <span>Add Task</span>
       </a>

     </div> 
     <hr/>
       <h4>Task List</h4>
     <hr/>

       <%if task_list(section["gid"])["data"].any?%>
           <%task_list(section["gid"])["data"].each do |task|%>
            <li class="task-list"><p><%=task["name"]%> </p> <%= link_to "Update", edit_task_path(task['gid'])%> </li>
           <%end%>
       <%else%>
       <p class="no-task">No Task</p>
       <%end%>
         <div class="button-container">
            <%=link_to "Delete Section", destroy_section_path(section["gid"]), class: 'btn-link'%>
            <%=link_to "Update Section", edit_section_path(section["gid"]), class: 'btn-link'%>
         </div>
   </ul>
<%end%>
<%else%>
<div class="error-conatiner">
  <p><%=@body["errors"][0]["message"]%></p>
  <p><%=@body["errors"][0]["help"]%></p>
</div>
<%end%>
</div>

app/views/homes/new.html.erb
    <%= render "header"%>

<div class="form">
  <%= form_with url: "/project/sections", method: :post do |form| %>

   <div class='filed'>
    <%= form.label :name, "Section Name" %><br/><br/>
    <%= form.text_field :name, required: true, placeholder: 'section name' %>
  </div>
  <%= form.submit "Create Section", class: 'btn-link' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiWrapperForAsana</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>